description: Kosmas - The Definitive Resource
url: 'http://gallant-franklin-419d6e.netlify.app'
logo: /images/uploads/logo.png
og_image: /images/uploads/logo.png
google_analytics_site_verification: 7HV6y9sMCjcVViddswXPrmRjk9kbPEgFmb6XI5yVuQI
google_analytics_tracking_code: UA-115012704-1
