backend:
  name: github
  repo: msimmer/kosmas-systems # Path to your Github repository
  branch: master # Branch to update

media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "apparel" # Used in routes, e.g., /admin/collections/blog
    label: "Apparel" # Used in the UI
    folder: "_apparel" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    card: {type: "alltype", text: "title"}
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      # - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - name: gallery
        label: Gallery
        widget: list
        fields:
          - {label: "Alt Tag", name: alt, widget: string}
          - {label: Description, name: description, widget: markdown}
          - {label: Image, name: image, widget: image}
